 pip3 install google-cloud
 pip3 install google-cloud-functions
 pip3 install google-cloud-pubsub
 pip3 install google-cloud-datastore
 pip3 install -y docker
 pip3 install docker
 pip3 install wget
 pip3 install numpy
 pip3 install pandas
 pip3 install criticalpath
 pip3 install -y gekko
 pip3 install gekko
 pip3 install google.cloud
 pip3 install google.cloud.monitoring
 pip3 install google-cloud-monitoring
 pip3 install deque
 pip3 install collections

sudo  usermod -a -G docker  $1
sudo apt install -y docker.io
sudo apt install -y libcurl*
sudo apt install -y libcurl-devel

